@startuml

 class Contacto {
     - tipo: TipoContacto
     - valor: String
     - notificaciones: List<Notificacion>
     --
     + enviar(mensaje: String): void
     + reintentarFallidas(): void
     - intentarEnviar(notificacion: Notificacion): void
 }

 enum TipoContacto {
     WHATSAPP
     SMS
     EMAIL
     --
     + crearEstrategia(): EstrategiaDeNotificacion
 }
 enum EstadoNotificacion {
     PENDIENTE
     COMPLETADA
     FALLIDA
 }

 interface EstrategiaDeNotificacion {
     + enviar(destino: String, mensaje: String): boolean
 }

 class Notificacion {
     - mensaje: String
     - estado: EstadoNotificacion
     --
     + marcarComoCompletada(): void
     + marcarComoFallida(): void
 }

 class NotificacionPorEmail
 class NotificacionPorSMS
 class NotificacionPorWhatsApp

 ' Relaciones de Composición (Parte-Todo)
 Contacto "1" *-- "1" TipoContacto : define el
 Contacto "1" *-- "0..*" Notificacion : almacena
 Notificacion "1" *-- "1" EstadoNotificacion : tiene un

 ' Relaciones de Dependencia (Uso)
 Contacto ..> EstrategiaDeNotificacion : usa
 TipoContacto .left.> EstrategiaDeNotificacion : crea

 ' Relaciones de Herencia (Implementación)
 NotificacionPorEmail .up.|> EstrategiaDeNotificacion
 NotificacionPorSMS .up.|> EstrategiaDeNotificacion
 NotificacionPorWhatsApp .up.|> EstrategiaDeNotificacion

 @enduml