@startuml

 class Contacto {
     - estrategia: EstrategiaDeNotificacion
     - valor: String
     --
     + enviar(mensaje: String): boolean
 }

 enum EstadoNotificacion {
     PENDIENTE
     COMPLETADA
     FALLIDA
 }

 interface EstrategiaDeNotificacion {
     + enviar(destino: String, mensaje: String): boolean
 }

 class Notificacion {
     - mensaje: String
     - estado: EstadoNotificacion
     - contacto: Contacto
     --
     + enviar(mensaje: String): void
     + marcarComoCompletada(): void
     + marcarComoFallida(): void
 }

 class NotificacionPorEmail
 class NotificacionPorSMS
 class NotificacionPorWhatsApp

 ' Relaciones de Composición (Parte-Todo)
 Contacto "1" <-up- "1" Notificacion: tiene un
 Notificacion "1" --> "1" EstadoNotificacion : tiene un

 ' Relaciones de Dependencia (Uso)
 Contacto -left-> EstrategiaDeNotificacion : tiene

 ' Relaciones de Herencia (Implementación)
 NotificacionPorEmail .up.|> EstrategiaDeNotificacion : implementa
 NotificacionPorSMS .up.|> EstrategiaDeNotificacion : implementa
 NotificacionPorWhatsApp .up.|> EstrategiaDeNotificacion : implementa

 @enduml